/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './captcha';
import * as i2 from '@angular/common';
export const CaptchaModuleNgFactory:i0.NgModuleFactory<i1.CaptchaModule> = i0.ɵcmf(i1.CaptchaModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.CaptchaModule,i1.CaptchaModule,
          ([] as any[]))]);
    });
const styles_Captcha:any[] = ([] as any[]);
export const RenderType_Captcha:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Captcha,
    data:{}});
export function View_Captcha_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (null as any));
}
export function View_Captcha_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-captcha',([] as any[]),
      (null as any),(null as any),(null as any),View_Captcha_0,RenderType_Captcha)),
      i0.ɵdid(4374528,(null as any),0,i1.Captcha,[i0.ElementRef,i0.NgZone],(null as any),
          (null as any))],(null as any),(null as any));
}
export const CaptchaNgFactory:i0.ComponentFactory<i1.Captcha> = i0.ɵccf('p-captcha',
    i1.Captcha,View_Captcha_Host_0,{siteKey:'siteKey',theme:'theme',type:'type',size:'size',
        tabindex:'tabindex',language:'language',initCallback:'initCallback'},{onResponse:'onResponse',
        onExpire:'onExpire'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J3b2Jib25lcy9kZXYvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvY2FwdGNoYS9jYXB0Y2hhLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2J3b2Jib25lcy9kZXYvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvY2FwdGNoYS9jYXB0Y2hhLnRzIiwibmc6Ly8vVXNlcnMvYndvYmJvbmVzL2Rldi9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9jYXB0Y2hhL2NhcHRjaGEudHMuQ2FwdGNoYS5odG1sIiwibmc6Ly8vVXNlcnMvYndvYmJvbmVzL2Rldi9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9jYXB0Y2hhL2NhcHRjaGEudHMuQ2FwdGNoYV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+PC9kaXY+IiwiPHAtY2FwdGNoYT48L3AtY2FwdGNoYT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBOzs7O29CQ0FBO01BQUE7YUFBQTtVQUFBOzs7OzsifQ==
